highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: "" # Required: replace this with your domain
name: IS-UNAH # Required: will be displayed on every page's header
title: Blog IS-UNAH # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - Notas
  - Tutoriales
description: "Blog creado para la difusión de temas de la Carrera de Ingeniería en Sistemas de la UNAH" # Required

disqus:
  comments: false # Global toggle on/off disqus comment
  shortname: disqus # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  demo_series:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"